#!/usr/bin/env bash
set -euo pipefail

# Download Google Material Symbols as GNOME symbolic icons
# Output: src/symbolic/{category}/{name}-symbolic.svg

BASE_URL="https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT_DIR="${SCRIPT_DIR}/src/symbolic"

mkdir -p "${OUT_DIR}"/{actions,apps,categories,devices,emblems,emotes,mimetypes,places,status,ui}

# Convert a Material SVG to GNOME symbolic format (16x16, fill=#2e3436)
convert_svg() {
  local input="$1"
  local output="$2"
  # Extract just the path data, wrap in 16x16 SVG
  # Material uses viewBox="0 -960 960 960" — keep it but set size to 16
  sed \
    -e 's/height="24"/height="16px"/' \
    -e 's/width="24"/width="16px"/' \
    -e 's/<path /<path fill="#2e3436" /' \
    "$input" > "$output"
}

# Download and convert a single icon
# Usage: fetch MATERIAL_NAME CATEGORY SYMBOLIC_NAME
fetch() {
  local mat_name="$1"
  local category="$2"
  local sym_name="$3"
  local url="${BASE_URL}/${mat_name}/default/24px.svg"
  local tmp="/tmp/mat_${mat_name}.svg"
  local dest="${OUT_DIR}/${category}/${sym_name}-symbolic.svg"

  if [ -f "$dest" ]; then
    return 0
  fi

  if [ ! -f "$tmp" ]; then
    if ! curl -sf "$url" -o "$tmp" 2>/dev/null; then
      echo "  FAIL: ${mat_name} → ${sym_name}" >&2
      return 0
    fi
  fi
  convert_svg "$tmp" "$dest"
  echo "  OK: ${sym_name}-symbolic.svg"
}

echo "=== Downloading Material Symbols as GNOME symbolic icons ==="

echo ""
echo "--- actions ---"
# Document actions
fetch "note_add" actions "document-new"
fetch "folder_open" actions "document-open"
fetch "history" actions "document-open-recent"
fetch "save" actions "document-save"
fetch "save_as" actions "document-save-as"
fetch "print" actions "document-print"
fetch "print" actions "document-print-preview"
fetch "description" actions "document-properties"
fetch "settings_backup_restore" actions "document-revert"
fetch "settings_backup_restore" actions "document-revert-rtl"
fetch "settings_backup_restore" actions "document-revert-symbolic-rtl"
fetch "tune" actions "document-page-setup"
fetch "send" actions "document-send"
fetch "edit" actions "document-edit"
fetch "exit_to_app" actions "application-exit"
fetch "exit_to_app" actions "application-exit-rtl"
fetch "exit_to_app" actions "application-exit-symbolic-rtl"
fetch "block" actions "action-unavailable"

# Edit actions
fetch "content_copy" actions "edit-copy"
fetch "content_cut" actions "edit-cut"
fetch "content_paste" actions "edit-paste"
fetch "delete" actions "edit-delete"
fetch "search" actions "edit-find"
fetch "find_replace" actions "edit-find-replace"
fetch "undo" actions "edit-undo"
fetch "undo" actions "edit-undo-symbolic-rtl"
fetch "redo" actions "edit-redo"
fetch "redo" actions "edit-redo-symbolic-rtl"
fetch "select_all" actions "edit-select-all"
fetch "select" actions "edit-select"
fetch "backspace" actions "edit-clear"
fetch "backspace" actions "edit-clear-rtl"
fetch "backspace" actions "edit-clear-symbolic-rtl"
fetch "clear_all" actions "edit-clear-all"
fetch "spellcheck" actions "error-correct"

# Navigation
fetch "home" actions "go-home"
fetch "chevron_right" actions "go-next"
fetch "chevron_left" actions "go-next-symbolic-rtl"
fetch "chevron_left" actions "go-previous"
fetch "chevron_right" actions "go-previous-symbolic-rtl"
fetch "arrow_upward" actions "go-up"
fetch "arrow_downward" actions "go-down"
fetch "vertical_align_top" actions "go-top"
fetch "vertical_align_bottom" actions "go-bottom"
fetch "first_page" actions "go-first"
fetch "last_page" actions "go-first-symbolic-rtl"
fetch "last_page" actions "go-last"
fetch "first_page" actions "go-last-symbolic-rtl"
fetch "open_in_new" actions "go-jump"
fetch "open_in_new" actions "go-jump-rtl"
fetch "open_in_new" actions "go-jump-symbolic-rtl"

# View
fetch "fullscreen" actions "view-fullscreen"
fetch "fullscreen_exit" actions "view-restore"
fetch "refresh" actions "view-refresh"
fetch "grid_view" actions "view-grid"
fetch "apps" actions "view-app-grid"
fetch "view_list" actions "view-list"
fetch "view_list" actions "view-list-rtl"
fetch "view_list" actions "view-list-symbolic-rtl"
fetch "format_list_bulleted" actions "view-list-bullet"
fetch "format_list_bulleted" actions "view-list-bullet-rtl"
fetch "format_list_bulleted" actions "view-list-bullet-symbolic-rtl"
fetch "format_list_numbered" actions "view-list-ordered"
fetch "format_list_numbered" actions "view-list-ordered-rtl"
fetch "format_list_numbered" actions "view-list-ordered-symbolic-rtl"
fetch "auto_stories" actions "view-paged"
fetch "auto_stories" actions "view-paged-rtl"
fetch "auto_stories" actions "view-paged-symbolic-rtl"
fetch "view_column" actions "view-dual"
fetch "view_day" actions "view-continuous"
fetch "flip" actions "view-mirror"
fetch "more_vert" actions "view-more"
fetch "more_horiz" actions "view-more-horizontal"
fetch "push_pin" actions "view-pin"
fetch "visibility" actions "view-reveal"
fetch "visibility_off" actions "view-conceal"
fetch "sort" actions "view-sort-ascending"
fetch "sort" actions "view-sort-ascending-rtl"
fetch "sort" actions "view-sort-ascending-symbolic-rtl"
fetch "sort" actions "view-sort-descending"
fetch "sort" actions "view-sort-descending-rtl"
fetch "sort" actions "view-sort-descending-symbolic-rtl"

# Zoom
fetch "zoom_in" actions "zoom-in"
fetch "zoom_out" actions "zoom-out"
fetch "fit_screen" actions "zoom-fit-best"
fetch "crop_free" actions "zoom-original"

# Media
fetch "play_arrow" actions "media-playback-start"
fetch "pause" actions "media-playback-pause"
fetch "stop" actions "media-playback-stop"
fetch "skip_next" actions "media-skip-forward"
fetch "skip_next" actions "media-skip-forward-symbolic-rtl"
fetch "skip_previous" actions "media-skip-backward"
fetch "skip_previous" actions "media-skip-backward-symbolic-rtl"
fetch "fast_forward" actions "media-seek-forward"
fetch "fast_forward" actions "media-seek-forward-symbolic-rtl"
fetch "fast_rewind" actions "media-seek-backward"
fetch "fast_rewind" actions "media-seek-backward-symbolic-rtl"
fetch "fiber_manual_record" actions "media-record"
fetch "eject" actions "media-eject"
fetch "subtitles" actions "media-view-subtitles"

# Formatting
fetch "format_bold" actions "format-text-bold"
fetch "format_italic" actions "format-text-italic"
fetch "format_underlined" actions "format-text-underline"
fetch "strikethrough_s" actions "format-text-strikethrough"
fetch "format_align_left" actions "format-justify-left"
fetch "format_align_center" actions "format-justify-center"
fetch "format_align_right" actions "format-justify-right"
fetch "format_align_justify" actions "format-justify-fill"
fetch "format_indent_increase" actions "format-indent-more"
fetch "format_indent_increase" actions "format-indent-more-rtl"
fetch "format_indent_increase" actions "format-indent-more-symbolic-rtl"
fetch "format_indent_decrease" actions "format-indent-less"
fetch "format_indent_decrease" actions "format-indent-less-rtl"
fetch "format_indent_decrease" actions "format-indent-less-symbolic-rtl"
fetch "format_clear" actions "format-text-plaintext"
fetch "text_format" actions "format-text-rich"
fetch "format_textdirection_l_to_r" actions "format-text-direction"
fetch "format_textdirection_r_to_l" actions "format-text-direction-rtl"
fetch "format_textdirection_r_to_l" actions "format-text-direction-symbolic-rtl"

# Insert
fetch "image" actions "insert-image"
fetch "link" actions "insert-link"
fetch "widgets" actions "insert-object"
fetch "text_fields" actions "insert-text"

# Misc actions
fetch "add" actions "list-add"
fetch "remove" actions "list-remove"
fetch "delete_sweep" actions "list-remove-all"
fetch "menu" actions "open-menu"
fetch "search" actions "system-search"
fetch "power_settings_new" actions "system-shutdown"
fetch "restart_alt" actions "system-reboot"
fetch "logout" actions "system-log-out"
fetch "logout" actions "system-log-out-rtl"
fetch "logout" actions "system-log-out-symbolic-rtl"
fetch "terminal" actions "system-run"
fetch "add" actions "tab-new"
fetch "bookmark_add" actions "bookmark-new"
fetch "star" actions "star-new"
fetch "close" actions "process-stop"
fetch "share" actions "send-to"
fetch "my_location" actions "find-location"
fetch "add_location" actions "mark-location"
fetch "contacts" actions "address-book-new"
fetch "event" actions "appointment-new"
fetch "chat" actions "chat-message-new"
fetch "contact_page" actions "contact-new"
fetch "email" actions "mail-message-new"
fetch "forward_to_inbox" actions "mail-send-receive"
fetch "send" actions "mail-send"
fetch "forward" actions "mail-forward"
fetch "forward" actions "mail-forward-symbolic-rtl"
fetch "reply" actions "mail-reply-sender"
fetch "reply" actions "mail-reply-sender-symbolic-rtl"
fetch "reply_all" actions "mail-reply-all"
fetch "reply_all" actions "mail-reply-all-rtl"
fetch "reply_all" actions "mail-reply-all-symbolic-rtl"
fetch "priority_high" actions "mail-mark-important"
fetch "report" actions "mail-mark-junk"
fetch "verified" actions "mail-mark-notjunk"
fetch "call" actions "call-start"
fetch "call_end" actions "call-stop"
fetch "cameraswitch" actions "camera-switch"
fetch "font_download" actions "font-select"
fetch "palette" actions "color-select"
fetch "checklist" actions "selection-mode"
fetch "person_add" actions "system-switch-user"
fetch "person_add" actions "system-switch-user-rtl"
fetch "person_add" actions "system-switch-user-symbolic-rtl"
fetch "flip_camera_android" actions "object-flip-horizontal"
fetch "flip_camera_android" actions "object-flip-vertical"
fetch "rotate_left" actions "object-rotate-left"
fetch "rotate_right" actions "object-rotate-right"
fetch "check_circle" actions "object-select"
fetch "create_new_folder" actions "folder-new"
fetch "spellcheck" actions "tools-check-spelling"
fetch "remove" actions "value-decrease"
fetch "add" actions "value-increase"
fetch "right_panel_open" actions "sidebar-show"
fetch "right_panel_open" actions "sidebar-show-symbolic-rtl"
fetch "left_panel_open" actions "sidebar-show-right"
fetch "left_panel_open" actions "sidebar-show-right-symbolic-rtl"

echo ""
echo "--- apps ---"
fetch "help" apps "help-contents"

echo ""
echo "--- categories ---"
fetch "settings" categories "preferences-desktop"
fetch "build" categories "preferences-other"
fetch "security" categories "preferences-system"
fetch "palette" categories "preferences-desktop-appearance"
fetch "language" categories "preferences-desktop-locale"
fetch "accessibility" categories "preferences-desktop-accessibility"
fetch "notifications" categories "preferences-desktop-notifications"
fetch "keyboard" categories "preferences-desktop-keyboard"
fetch "wallpaper" categories "preferences-desktop-wallpaper"
fetch "display_settings" categories "preferences-desktop-display"
fetch "screen_share" categories "preferences-desktop-remote-desktop"
fetch "dns" categories "preferences-system-network"
fetch "schedule" categories "preferences-system-time"
fetch "share" categories "preferences-system-sharing"
fetch "power_settings_new" categories "preferences-system-power"
fetch "privacy_tip" categories "preferences-system-privacy"
fetch "search" categories "preferences-system-search"
fetch "manage_accounts" categories "preferences-system-users"
fetch "devices" categories "preferences-system-devices"
fetch "info" categories "preferences-system-details"

echo ""
echo "--- devices ---"
fetch "speaker" devices "audio-speakers"
fetch "speaker" devices "audio-speakers-rtl"
fetch "speaker" devices "audio-speakers-symbolic-rtl"
fetch "headphones" devices "audio-headphones"
fetch "headset_mic" devices "audio-headset"
fetch "mic" devices "audio-input-microphone"
fetch "speaker_group" devices "audio-card"
fetch "battery_full" devices "battery"
fetch "bluetooth" devices "bluetooth"
fetch "photo_camera" devices "camera-photo"
fetch "videocam" devices "camera-video"
fetch "linked_camera" devices "camera-web"
fetch "computer" devices "computer"
fetch "cast" devices "display-projector"
fetch "hard_drive" devices "drive-harddisk"
fetch "hard_drive" devices "drive-harddisk-solidstate"
fetch "hard_drive" devices "drive-harddisk-system"
fetch "usb" devices "drive-harddisk-usb"
fetch "hard_drive" devices "drive-harddisk-ieee1394"
fetch "storage" devices "drive-multidisk"
fetch "album" devices "drive-optical"
fetch "usb" devices "drive-removable-media"
fetch "dialpad" devices "input-dialpad"
fetch "sports_esports" devices "input-gaming"
fetch "keyboard" devices "input-keyboard"
fetch "mouse" devices "input-mouse"
fetch "touch_app" devices "input-touchpad"
fetch "tablet" devices "input-tablet"
fetch "sd_storage" devices "media-flash"
fetch "save" devices "media-floppy"
fetch "disc_full" devices "media-optical"
fetch "disc_full" devices "media-optical-bd"
fetch "disc_full" devices "media-optical-cd"
fetch "disc_full" devices "media-optical-cd-audio"
fetch "disc_full" devices "media-optical-dvd"
fetch "sd_card" devices "media-removable"
fetch "cassette" devices "media-tape"
fetch "folder_zip" devices "media-zip"
fetch "router" devices "modem"
fetch "headphones" devices "multimedia-player"
fetch "headphones" devices "multimedia-player-apple-ipod-touch"
fetch "signal_cellular_4_bar" devices "network-cellular"
fetch "lan" devices "network-wired"
fetch "wifi" devices "network-wireless"
fetch "smartphone" devices "phone"
fetch "smartphone" devices "phone-apple-iphone"
fetch "phone" devices "phone-old"
fetch "phone_android" devices "pda"
fetch "print" devices "printer"
fetch "print" devices "printer-network"
fetch "scanner" devices "scanner"
fetch "tablet_mac" devices "tablet"
fetch "bolt" devices "thunderbolt"
fetch "tv" devices "tv"
fetch "battery_charging_full" devices "uninterruptible-power-supply"
fetch "monitor" devices "video-display"
fetch "desktop_windows" devices "video-joined-displays"
fetch "desktop_windows" devices "video-single-display"
fetch "computer" devices "computer-apple-ipad"
fetch "colorize" devices "colorimeter-colorhug"
fetch "power" devices "ac-adapter"
fetch "sim_card" devices "auth-sim"
fetch "face" devices "auth-face"
fetch "fingerprint" devices "auth-fingerprint"
fetch "credit_card" devices "auth-smartcard"

echo ""
echo "--- emblems ---"
fetch "favorite" emblems "emblem-favorite"
fetch "photo" emblems "emblem-photos"
fetch "share" emblems "emblem-shared"
fetch "sync" emblems "emblem-synchronizing"
fetch "link" emblems "emblem-symbolic-link"
fetch "flag" emblems "emblem-important"
fetch "description" emblems "emblem-documents"
fetch "music_note" emblems "emblem-music"
fetch "videocam" emblems "emblem-videos"
fetch "download" emblems "emblem-downloads"
fetch "lock" emblems "emblem-readonly"

echo ""
echo "--- emotes ---"
fetch "sentiment_very_satisfied" emotes "face-angel"
fetch "mood" emotes "face-smile"
fetch "mood_bad" emotes "face-sad"
fetch "sentiment_very_dissatisfied" emotes "face-angry"
fetch "sentiment_neutral" emotes "face-plain"
fetch "sick" emotes "face-sick"
fetch "sentiment_dissatisfied" emotes "face-worried"
fetch "sentiment_very_satisfied" emotes "face-laugh"
fetch "sentiment_satisfied" emotes "face-cool"
fetch "wink" emotes "face-wink"
fetch "cruelty_free" emotes "face-monkey"
fetch "sentiment_stressed" emotes "face-crying"
fetch "thumb_up" emotes "face-yawn"
fetch "emoji_people" emotes "face-glasses"
fetch "sentiment_extremely_dissatisfied" emotes "face-devilish"
fetch "sentiment_frustrated" emotes "face-confused"
fetch "emoji_emotions" emotes "face-embarrassed"
fetch "sentiment_excited" emotes "face-surprise"
fetch "sentiment_calm" emotes "face-tired"
fetch "self_improvement" emotes "face-uncertain"
fetch "emoji_emotions" emotes "face-raspberry"
fetch "sentiment_content" emotes "face-smirk"
fetch "do_not_disturb" emotes "face-shutmouth"
fetch "emoji_food_beverage" emotes "face-kiss"
fetch "emoji_nature" emotes "face-smile-big"
fetch "psychology" emotes "face-thinking"

echo ""
echo "--- mimetypes ---"
fetch "description" mimetypes "text-x-generic"
fetch "code" mimetypes "text-x-script"
fetch "html" mimetypes "text-html"
fetch "image" mimetypes "image-x-generic"
fetch "movie" mimetypes "video-x-generic"
fetch "music_note" mimetypes "audio-x-generic"
fetch "folder" mimetypes "inode-directory"
fetch "insert_drive_file" mimetypes "application-x-generic"
fetch "archive" mimetypes "package-x-generic"
fetch "font_download" mimetypes "font-x-generic"
fetch "insert_drive_file" mimetypes "application-x-executable"
fetch "insert_drive_file" mimetypes "application-x-firmware"
fetch "terminal" mimetypes "application-x-sharedlib"
fetch "inventory_2" mimetypes "application-x-addon"
fetch "library_books" mimetypes "x-office-document"
fetch "table_chart" mimetypes "x-office-spreadsheet"
fetch "slideshow" mimetypes "x-office-presentation"
fetch "contacts" mimetypes "x-office-address-book"
fetch "event" mimetypes "x-office-calendar"
fetch "draw" mimetypes "x-office-drawing"

echo ""
echo "--- places ---"
fetch "folder" places "folder"
fetch "folder" places "folder-documents"
fetch "download" places "folder-download"
fetch "drag_indicator" places "folder-drag-accept"
fetch "library_music" places "folder-music"
fetch "photo_library" places "folder-pictures"
fetch "public" places "folder-publicshare"
fetch "cloud" places "folder-remote"
fetch "saved_search" places "folder-saved-search"
fetch "folder_special" places "folder-templates"
fetch "video_library" places "folder-videos"
fetch "dns" places "network-server"
fetch "workspaces" places "network-workgroup"
fetch "home" places "start-here"
fetch "home" places "user-home"
fetch "desktop_windows" places "user-desktop"
fetch "bookmarks" places "user-bookmarks"
fetch "delete" places "user-trash"

echo ""
echo "--- status ---"
# Audio volume
fetch "volume_up" status "audio-volume-high"
fetch "volume_up" status "audio-volume-high-rtl"
fetch "volume_up" status "audio-volume-high-symbolic-rtl"
fetch "volume_down" status "audio-volume-medium"
fetch "volume_down" status "audio-volume-medium-rtl"
fetch "volume_down" status "audio-volume-medium-symbolic-rtl"
fetch "volume_mute" status "audio-volume-low"
fetch "volume_mute" status "audio-volume-low-rtl"
fetch "volume_mute" status "audio-volume-low-symbolic-rtl"
fetch "volume_off" status "audio-volume-muted"
fetch "volume_off" status "audio-volume-muted-rtl"
fetch "volume_off" status "audio-volume-muted-symbolic-rtl"
fetch "volume_up" status "audio-volume-overamplified"
fetch "volume_up" status "audio-volume-overamplified-rtl"
fetch "volume_up" status "audio-volume-overamplified-symbolic-rtl"

# Battery
fetch "battery_alert" status "battery-action"
fetch "battery_alert" status "battery-caution"
fetch "battery_0_bar" status "battery-level-0"
fetch "battery_charging_full" status "battery-level-0-charging"
fetch "battery_1_bar" status "battery-level-10"
fetch "battery_charging_full" status "battery-level-10-charging"
fetch "battery_2_bar" status "battery-level-20"
fetch "battery_charging_full" status "battery-level-20-charging"
fetch "battery_3_bar" status "battery-level-30"
fetch "battery_charging_full" status "battery-level-30-charging"
fetch "battery_4_bar" status "battery-level-40"
fetch "battery_charging_full" status "battery-level-40-charging"
fetch "battery_5_bar" status "battery-level-50"
fetch "battery_charging_full" status "battery-level-50-charging"
fetch "battery_5_bar" status "battery-level-60"
fetch "battery_charging_full" status "battery-level-60-charging"
fetch "battery_6_bar" status "battery-level-70"
fetch "battery_charging_full" status "battery-level-70-charging"
fetch "battery_6_bar" status "battery-level-80"
fetch "battery_charging_full" status "battery-level-80-charging"
fetch "battery_full" status "battery-level-90"
fetch "battery_charging_full" status "battery-level-90-charging"
fetch "battery_full" status "battery-level-100"
fetch "battery_full" status "battery-level-100-charged"
fetch "battery_alert" status "battery-low"
fetch "battery_unknown" status "battery-missing"

# Bluetooth
fetch "bluetooth_connected" status "bluetooth-active"
fetch "bluetooth_searching" status "bluetooth-acquiring"
fetch "bluetooth_disabled" status "bluetooth-disabled"
fetch "bluetooth" status "bluetooth-disconnected"
fetch "bluetooth_disabled" status "bluetooth-hardware-disabled"

# Network - wireless
fetch "signal_wifi_4_bar" status "network-wireless-signal-excellent"
fetch "network_wifi_3_bar" status "network-wireless-signal-good"
fetch "network_wifi_2_bar" status "network-wireless-signal-ok"
fetch "network_wifi_1_bar" status "network-wireless-signal-weak"
fetch "signal_wifi_off" status "network-wireless-signal-none"
fetch "wifi_find" status "network-wireless-acquiring"
fetch "wifi" status "network-wireless-connected"
fetch "wifi_off" status "network-wireless-disabled"
fetch "wifi_lock" status "network-wireless-encrypted"
fetch "wifi_off" status "network-wireless-hardware-disabled"
fetch "wifi_tethering" status "network-wireless-hotspot"
fetch "wifi_off" status "network-wireless-no-route"
fetch "wifi_off" status "network-wireless-offline"

# Network - wired
fetch "lan" status "network-wired-acquiring"
fetch "lan" status "network-wired-disconnected"
fetch "lan" status "network-wired-no-route"

# Network - cellular
fetch "signal_cellular_4_bar" status "network-cellular-signal-excellent"
fetch "signal_cellular_4_bar" status "network-cellular-signal-excellent-rtl"
fetch "signal_cellular_4_bar" status "network-cellular-signal-excellent-symbolic-rtl"
fetch "network_cell" status "network-cellular-signal-good"
fetch "network_cell" status "network-cellular-signal-good-rtl"
fetch "network_cell" status "network-cellular-signal-good-symbolic-rtl"
fetch "signal_cellular_alt" status "network-cellular-signal-ok"
fetch "signal_cellular_alt" status "network-cellular-signal-ok-rtl"
fetch "signal_cellular_alt" status "network-cellular-signal-ok-symbolic-rtl"
fetch "signal_cellular_alt_1_bar" status "network-cellular-signal-weak"
fetch "signal_cellular_alt_1_bar" status "network-cellular-signal-weak-rtl"
fetch "signal_cellular_alt_1_bar" status "network-cellular-signal-weak-symbolic-rtl"
fetch "signal_cellular_off" status "network-cellular-signal-none"
fetch "signal_cellular_off" status "network-cellular-signal-none-rtl"
fetch "signal_cellular_off" status "network-cellular-signal-none-symbolic-rtl"
fetch "signal_cellular_4_bar" status "network-cellular-acquiring"
fetch "signal_cellular_4_bar" status "network-cellular-acquiring-rtl"
fetch "signal_cellular_4_bar" status "network-cellular-acquiring-symbolic-rtl"
fetch "signal_cellular_connected_no_internet_4_bar" status "network-cellular-connected"
fetch "signal_cellular_off" status "network-cellular-disabled"
fetch "signal_cellular_off" status "network-cellular-disabled-rtl"
fetch "signal_cellular_off" status "network-cellular-disabled-symbolic-rtl"
fetch "signal_cellular_off" status "network-cellular-hardware-disabled"
fetch "signal_cellular_off" status "network-cellular-hardware-disabled-rtl"
fetch "signal_cellular_off" status "network-cellular-hardware-disabled-symbolic-rtl"
fetch "signal_cellular_no_sim" status "network-cellular-no-route"
fetch "signal_cellular_no_sim" status "network-cellular-no-route-rtl"
fetch "signal_cellular_no_sim" status "network-cellular-no-route-symbolic-rtl"
fetch "signal_cellular_off" status "network-cellular-offline"
fetch "signal_cellular_off" status "network-cellular-offline-rtl"
fetch "signal_cellular_off" status "network-cellular-offline-symbolic-rtl"
fetch "lte_mobiledata" status "network-cellular-4g"
fetch "5g" status "network-cellular-5g"
fetch "3g_mobiledata" status "network-cellular-3g"
fetch "2mp" status "network-cellular-2g"
fetch "e_mobiledata" status "network-cellular-edge"
fetch "g_mobiledata" status "network-cellular-gprs"
fetch "h_mobiledata" status "network-cellular-hspa"

# Network - misc
fetch "error" status "network-error"
fetch "speed" status "network-idle"
fetch "cloud_off" status "network-no-route"
fetch "cloud_off" status "network-offline"
fetch "download" status "network-receive"
fetch "download" status "network-receive-symbolic-rtl"
fetch "upload" status "network-transmit"
fetch "upload" status "network-transmit-symbolic-rtl"
fetch "sync" status "network-transmit-receive"

# VPN
fetch "vpn_lock" status "network-vpn-acquiring"
fetch "vpn_lock" status "network-vpn-disconnected"
fetch "vpn_key_off" status "network-vpn-disabled"
fetch "vpn_key_off" status "network-vpn-no-route"
fetch "vpn_key" status "network-vpn"

# SIM
fetch "sim_card_alert" status "auth-sim-locked"
fetch "no_sim" status "auth-sim-missing"

# Misc status
fetch "flight" status "airplane-mode"
fetch "alarm" status "alarm"
fetch "event_busy" status "appointment-missed"
fetch "event_upcoming" status "appointment-soon"
fetch "account_circle" status "avatar-default"
fetch "dark_mode" status "night-light"
fetch "dark_mode" status "night-light-disabled"
fetch "brightness_medium" status "display-brightness"
fetch "keyboard" status "keyboard-brightness"
fetch "error" status "dialog-error"
fetch "warning" status "dialog-warning"
fetch "info" status "dialog-information"
fetch "help" status "dialog-question"
fetch "lock" status "dialog-password"
fetch "videocam_off" status "camera-disabled"
fetch "videocam_off" status "camera-hardware-disabled"
fetch "lock_open" status "changes-allow"
fetch "lock" status "changes-prevent"
fetch "no_encryption" status "channel-insecure"
fetch "https" status "channel-secure"
fetch "desktop_access_disabled" status "computer-fail"
fetch "hourglass_empty" status "content-loading"
fetch "wb_twilight" status "daytime-sunrise"
fetch "wb_twilight" status "daytime-sunset"
fetch "folder_open" status "folder-open"
fetch "drive_file_move" status "folder-visiting"
fetch "drag_indicator" status "folder-drag-accept"
fetch "image" status "image-loading"
fetch "broken_image" status "image-missing"
fetch "location_on" status "location-services-active"
fetch "location_off" status "location-services-disabled"
fetch "attach_file" status "mail-attachment"
fetch "mark_email_read" status "mail-read"
fetch "reply" status "mail-replied"
fetch "reply" status "mail-replied-rtl"
fetch "reply" status "mail-replied-symbolic-rtl"
fetch "mark_email_unread" status "mail-unread"
fetch "repeat" status "media-playlist-repeat"
fetch "repeat_one" status "media-playlist-repeat-song"
fetch "playlist_play" status "media-playlist-consecutive"
fetch "shuffle" status "media-playlist-shuffle"
fetch "mic_off" status "microphone-disabled"
fetch "mic_off" status "microphone-hardware-disabled"
fetch "mic" status "microphone-sensitivity-high"
fetch "mic" status "microphone-sensitivity-medium"
fetch "mic" status "microphone-sensitivity-low"
fetch "mic_off" status "microphone-sensitivity-muted"
fetch "notifications_off" status "notifications-disabled"
fetch "screen_lock_landscape" status "orientation-landscape"
fetch "screen_lock_landscape" status "orientation-landscape-inverse"
fetch "screen_lock_portrait" status "orientation-portrait-left"
fetch "screen_lock_portrait" status "orientation-portrait-left-symbolic-rtl"
fetch "screen_lock_portrait" status "orientation-portrait-right"
fetch "screen_lock_portrait" status "orientation-portrait-right-symbolic-rtl"
fetch "eco" status "power-profile-balanced"
fetch "eco" status "power-profile-balanced-rtl"
fetch "eco" status "power-profile-balanced-symbolic-rtl"
fetch "speed" status "power-profile-performance"
fetch "speed" status "power-profile-performance-rtl"
fetch "speed" status "power-profile-performance-symbolic-rtl"
fetch "battery_saver" status "power-profile-power-saver"
fetch "battery_saver" status "power-profile-power-saver-rtl"
fetch "battery_saver" status "power-profile-power-saver-symbolic-rtl"
fetch "print" status "printer-printing"
fetch "error" status "printer-error"
fetch "warning" status "printer-warning"
fetch "screen_rotation" status "rotation-allowed"
fetch "screen_lock_rotation" status "rotation-locked"
fetch "screen_share" status "screen-shared"
fetch "verified_user" status "security-high"
fetch "security" status "security-medium"
fetch "security" status "security-medium-rtl"
fetch "security" status "security-medium-symbolic-rtl"
fetch "gpp_bad" status "security-low"
fetch "star_half" status "semi-starred"
fetch "star_half" status "semi-starred-rtl"
fetch "star_half" status "semi-starred-symbolic-rtl"
fetch "system_update" status "software-update-available"
fetch "system_update" status "software-update-urgent"
fetch "star" status "starred"
fetch "star_border" status "non-starred"
fetch "lock" status "system-lock-screen"
fetch "assignment_turned_in" status "task-due"
fetch "assignment_late" status "task-past-due"
fetch "bolt" status "thunderbolt-acquiring"
fetch "touch_app" status "touch-disabled"
fetch "touch_app" status "touchpad-disabled"
fetch "circle" status "user-available"
fetch "schedule" status "user-away"
fetch "do_not_disturb" status "user-busy"
fetch "hourglass_empty" status "user-idle"
fetch "visibility_off" status "user-invisible"
fetch "help" status "user-not-tracked"
fetch "cancel" status "user-offline"
fetch "pending" status "user-status-pending"
fetch "delete_forever" status "user-trash-full"
fetch "wrap_text" status "view-wrapped"
fetch "wrap_text" status "view-wrapped-rtl"
fetch "wrap_text" status "view-wrapped-symbolic-rtl"
fetch "call_received" status "call-incoming"
fetch "call_missed" status "call-missed"
fetch "call_made" status "call-outgoing"

# Weather
fetch "wb_sunny" status "weather-clear"
fetch "nights_stay" status "weather-clear-night"
fetch "partly_cloudy_day" status "weather-few-clouds"
fetch "partly_cloudy_night" status "weather-few-clouds-night"
fetch "foggy" status "weather-fog"
fetch "cloud" status "weather-overcast"
fetch "thunderstorm" status "weather-severe-alert"
fetch "grain" status "weather-showers-scattered"
fetch "rainy" status "weather-showers"
fetch "ac_unit" status "weather-snow"
fetch "thunderstorm" status "weather-storm"
fetch "cyclone" status "weather-tornado"
fetch "air" status "weather-windy"

echo ""
echo "--- ui ---"
fetch "check_box" ui "checkbox-checked"
fetch "check_box_outline_blank" ui "checkbox"
fetch "indeterminate_check_box" ui "checkbox-mixed"
fetch "radio_button_checked" ui "radio-checked"
fetch "radio_button_unchecked" ui "radio"
fetch "radio_button_checked" ui "radio-mixed"
fetch "close" ui "window-close"
fetch "crop_square" ui "window-maximize"
fetch "minimize" ui "window-minimize"
fetch "open_in_new" ui "window-new"
fetch "filter_none" ui "window-restore"
fetch "expand_more" ui "pan-down"
fetch "expand_less" ui "pan-up"
fetch "chevron_right" ui "pan-end"
fetch "chevron_left" ui "pan-end-symbolic-rtl"
fetch "chevron_left" ui "pan-start"
fetch "chevron_right" ui "pan-start-symbolic-rtl"
fetch "drag_handle" ui "list-drag-handle"
fetch "select_all" ui "selection-start"
fetch "select_all" ui "selection-start-symbolic-rtl"
fetch "deselect" ui "selection-end"
fetch "deselect" ui "selection-end-symbolic-rtl"
fetch "arrow_upward" ui "focus-top-bar"
fetch "grid_view" ui "focus-windows"
fetch "notifications" ui "focus-legacy-systray"

echo ""
echo "=== Done! ==="
echo "Cleaning up temp files..."
rm -f /tmp/mat_*.svg
echo "Total symbolic icons:"
find "${OUT_DIR}" -name "*-symbolic.svg" | wc -l